server:
  port: 9192

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        transaction:
          jta:
            platform: hibernate.transaction.jta.platform
    hibernate:
      ddl-auto: update

  datasource:
    username: root
    password: pawankalya@2
    url: jdbc:mysql://localhost:3306/Royal_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

  security:
    jwt:
      secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
      expire-length: 3600000
